name: bbs-go-docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: './docs/yarn.lock'
      - name: build
        working-directory: ./docs
        run: |
          cd docs
          yarn
          yarn docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          working-directory: ./docs/.vuepress/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/docs/.vuepress/dist
          cname: docs.bbs-go.com

